### ISSUE TITLE
Сompile errors.

### ISSUE THREAD

**Issue by Anoskin** [niXman/binapi#67] opened 2022-11-13 16:47 UTC
[log.txt](https://github.com/niXman/binapi/files/9997775/log.txt)

OS Linux Ubuntu 16.4. How can I correct errors

**Comment by niXman** [comment] 2022-11-13 20:02
how did you get this log?

**Comment by Anoskin** [comment] 2022-11-14 05:36
> how did you get this log?

cmake .
make -j4
![изображение](https://user-images.githubusercontent.com/50116181/201583395-4ad3f10b-b96e-4cda-9c4f-6b58f0e4237d.png)

**Comment by niXman** [comment] 2022-11-14 07:57
ok, now I have understand that you trying to build the test project...

gcc version?
boost version?

I think that's the reason...

**Comment by Anoskin** [comment] 2022-11-14 08:50
> ok, now I have understand that you trying to build the test project...
> 
> gcc version? boost version?
> 
> I think that's the reason...

Boost 1.66
gcc - I will only be able to see it tonight, but which one do you need?

**Comment by niXman** [comment] 2022-11-14 08:58
> Boost 1.66

AFAIR 1.70 min is required.

> but which one do you need?

with good c++14 support, at least 8 I think...

**Comment by Anoskin** [comment] 2022-11-14 09:04
> with good c++14 support, at least 8 I think...

Thanks

**Comment by Anoskin** [comment] 2022-11-14 17:14
![изображение](https://user-images.githubusercontent.com/50116181/201723566-c86e17d9-3881-4333-8b22-8918b06b152b.png)
Boost 1.8
gcc 10

**Comment by Anoskin** [comment] 2022-11-14 17:15
Errors save

**Comment by niXman** [comment] 2022-11-14 17:38
the first error message on the screenshot tells that `unique_ptr` can't be copied, and its true. in that line `std::move()` is used.

did you change anything on the corresponding CMakeLists file?

**Comment by Anoskin** [comment] 2022-11-14 17:47
> the first error message on the screenshot tells that `unique_ptr` can't be copied, and its true. in that line `std::move()` is used.
> 
> did you change anything on the corresponding CMakeLists file?

No. I just wanted to build as is before using it in my project

**Comment by niXman** [comment] 2022-11-14 18:00
![image](https://user-images.githubusercontent.com/518474/201731210-c5cddea5-962c-43f8-a406-c1e99a88fd0f.png)

compiler and boost infos:
![image](https://user-images.githubusercontent.com/518474/201731730-7797169d-bdea-461f-afda-b115925794e2.png)

so I think the issue is because of the old compiler. try to update to more recent one.
also make sure which GCC version is really used by cmake. or: `CC=gcc-<version> CXX=g++-<version> cmake .....`

**Comment by Anoskin** [comment] 2022-11-14 18:04
Good. Thanks

**Comment by niXman** [comment] 2022-11-15 13:07
@Anoskin is it solved? if yes - please close the issue.

**Comment by niXman** [comment] 2022-11-15 15:01
hmm...

**Closed** 2022-11-15 15:00 UTC
