### ISSUE TITLE
Failed to get markets data

### ISSUE THREAD

**Issue by Tsunami-lj** [niXman/binapi#43] opened 2021-08-18 15:16 UTC
Hi,  I try to replace mini_tickers with markets in the examples/websockets/main.cpp. 
Then I got the assert failed.

ws_test: src/websocket.cpp:302: binapi::ws::websockets::impl::start_channel(const char*, const char*, F) [with F = std::function<bool(const char*, int, std::__cxx11::basic_string<char>, binapi::ws::markets_tickers_t)>; binapi::ws::websockets::handle = void*]::<lambda(const char*, int, std::string, const char*, std::size_t)>: Assertion `json.is_valid()' failed.

Could you have a look at this. Thank you for your time and looking forward to your reply.

**Comment by niXman** [comment] 2021-08-19 09:59
> replace mini_tickers with markets

hmm... but it works for me.

**Comment by Tsunami-lj** [comment] 2021-08-19 13:16
> > replace mini_tickers with markets
> 
> hmm... but it works for me.

So why not return false in this case? Would we miss something?

**Comment by Tsunami-lj** [comment] 2021-08-19 13:25
> > So why not return false in this case?
> 
> where?
> please explain.
> 
> I think you faced with: #31

Indeed it's not the same.
Maybe we can repalce  `assert(json.is_valid()); ` with  ` if (json.is_valid()) return false;` in function `websockets::handle start_channel(const char *pair, const char *channel, F cb) ` in path binapi/src/websocket.cpp

**Comment by niXman** [comment] 2021-08-19 13:29
I'm using this implementation for my trading bot, and I would not like to think about the fact that I could forget to check some bool and my bot will start doing nonsense! better let it fall!

**Comment by niXman** [comment] 2021-08-19 13:32
if you provided me with the content of the response from the exchange before JSON parser, I would try to understand why this error occurs only for you.

**Comment by Tsunami-lj** [comment] 2021-08-19 13:36
> I'm using this implementation for my trading bot, and I would not like to think about the fact that I could forget to check some bool and my bot will start doing nonsense! better let it fall!



> if you provided me with the content of the response from the exchange before JSON parser, I would try to understand why this error occurs only for you.

Actually, I add print `ptr` before assert to debug. It got nothing,  and the program crash with segmentation fault. so it seems we got an empty message? By the way, I want to collect markets of all symbols, so the information will be very large, and when I got an empty message, I wish it can ignore it.

**Comment by Tsunami-lj** [comment] 2021-08-19 13:39
> > I'm using this implementation for my trading bot, and I would not like to think about the fact that I could forget to check some bool and my bot will start doing nonsense! better let it fall!
> 
> > if you provided me with the content of the response from the exchange before JSON parser, I would try to understand why this error occurs only for you.
> 
> Actually, I add print `ptr` before assert to debug. It got nothing, and the program crash with segmentation fault. so it seems we got an empty message? By the way, I want to collect markets of all symbols, so the information will be very large, and when I got an empty message, I wish it can ignore it.

When it crash, print nothing before assert. It can run for a while rather than crash as soon as I start it.

**Comment by niXman** [comment] 2021-08-19 13:39
binance should not send an empty response, at least I do not see this statement in the API documentation.
moreover, I never get an empty answer.

**Comment by Tsunami-lj** [comment] 2021-08-19 13:41
> binance should not send an empty response, at least I do not see this statement in the API documentation.
> moreover, I never get an empty answer.

I suscribe all symbols' markets, I have no idea whether it’s  the reason.

**Comment by Tsunami-lj** [comment] 2021-08-19 13:52
There are totally about 1600 symbols, I subscribe their markets all together. Then I meet the mistake, so could you try to reproduce it at your convenience. Many thanks for you.

**Comment by niXman** [comment] 2021-08-19 14:50
sure, I can check this when I can get an empty response from binance. unfortunately I never got an empty answer...

**Comment by Tsunami-lj** [comment] 2021-08-19 15:57
> hen I can get an empty response fr

Maybe you can also subscribe all symbols to check if it will fail to assert. I can provide the symbol list if you need it. : )

**Comment by niXman** [comment] 2021-08-19 16:00
> I can provide the symbol list if you need it

yes please

**Comment by Tsunami-lj** [comment] 2021-08-20 00:44
> > I can provide the symbol list if you need it
> 
> yes please
[binance_symbols.csv](https://github.com/niXman/binapi/files/7018336/binance_symbols.csv)

**Comment by Tsunami-lj** [comment] 2021-08-20 00:45
> > I can provide the symbol list if you need it
> 
> yes please

[binance_symbols.csv](https://github.com/niXman/binapi/files/7018338/binance_symbols.csv)
Thank you for your patience.

**Comment by niXman** [comment] 2021-08-20 07:03
> There are totally about 1600 symbols, I subscribe their markets all together.

please provide that code too.

**Comment by Tsunami-lj** [comment] 2021-08-20 07:30
> > There are totally about 1600 symbols, I subscribe their markets all together.
> 
> please provide that code too.

```
    ifstream symbolsFile("/home/binance_symbols.csv");
    string symbol;
    while (getline(symbolsFile, symbol)) {
        ws.part_depth(symbol.c_str(), binapi::e_levels::_20, binapi::e_freq::_100ms,
            [&logger, symbol](const char* fl, int ec, std::string emsg, auto depths) {
                if (ec) {
                    std::cerr << "subscribe part_depth error: fl=" << fl << ", ec=" << ec << ", emsg=" << emsg << std::endl;

                    return false;
                }
                
                 std::cout << symbol << ' ' << "part_depths: " << depths << std::endl;
                return true;
            }
        );
    }
```

**Comment by niXman** [comment] 2021-08-20 07:30
thanks

**Comment by niXman** [comment] 2021-08-20 11:45
I can confirm it is binance disconnects the connection, because the websocket at this moment gives an End Of File error.

at first I got this error using multiple connections like in your example. later in a cafe I got the same error when using one markets() connection.

so buy a wider internet channel and please close this issue.

**Comment by niXman** [comment] 2021-08-20 11:48
I will redo that part of code so that in case of a socket error I will report this before parsing the JSON.

**Comment by niXman** [comment] 2021-08-20 15:22
done: https://github.com/niXman/binapi/commit/656fe450008ab086570d9af1244c6133249a6f90

please close.

**Comment by Tsunami-lj** [comment] 2021-08-20 16:02
> done: [656fe45](https://github.com/niXman/binapi/commit/656fe450008ab086570d9af1244c6133249a6f90)
> 
> please close.

Well Done ! BTW, except for the the report part,  glad to see `return false`

**Comment by Tsunami-lj** [comment] 2021-08-20 16:06
> I can confirm it is binance disconnects the connection, because the websocket at this moment gives an End Of File error.
> 
> at first I got this error using multiple connections like in your example. later in a cafe I got the same error when using one markets() connection.
> 
> so buy a wider internet channel and please close this issue.

Actually, at first I met the error with markets. And that's why I made this title. Anyway, thanks for your prompt reply again. : )

**Closed** 2021-08-20 16:07 UTC
