### ISSUE TITLE
Issue Websocket Limitations

### ISSUE THREAD

**Issue by kyo06** [niXman/binapi#8] opened 2021-01-08 07:31 UTC
Hi niXman,

Thank you very much for your code.
I have an issue with websocket api, regards to the documentation as below :

General WSS information
The base endpoint is: wss://stream.binance.com:9443
Streams can be accessed either in a single raw stream or in a combined stream
Raw streams are accessed at /ws/<streamName>
Combined streams are accessed at /stream?streams=<streamName1>/<streamName2>/<streamName3>
Combined stream events are wrapped as follows: {"stream":"<streamName>","data":<rawPayload>}
All symbols for streams are lowercase
A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark
The websocket server will send a ping frame every 3 minutes. If the websocket server does not receive a pong frame back from the connection within a 10 minute period, the connection will be disconnected. Unsolicited pong frames are allowed.
Websocket Limits
WebSocket connections have a limit of 5 incoming messages per second. A message is considered:
A PING frame
A PONG frame
A JSON controlled message (e.g. subscribe, unsubscribe)
A connection that goes beyond the limit will be disconnected; IPs that are repeatedly disconnected may be banned.
A single connection can listen to a maximum of 1024 streams.

There is no pong message sending method after receiving a ping frame in the code every 3 minute.
Can you fix it or add pong method on websocket api ?

Can you add the streams limit (1024) regarding to the limitation ?
Can you add websocket reconnect method because it is closed after 24 hours ?

Thank you very much for your support :)

Best Regards

**Comment by niXman** [comment] 2021-01-09 06:18
hi,

> Can you fix it or add pong method on websocket api ?

will look at this...

> Can you add the streams limit (1024) regarding to the limitation ?

I think yes :)

> Can you add websocket reconnect method because it is closed after 24 hours ?

no, because I think it should be implemented above the level, i.e. by the user of this code...

**Comment by niXman** [comment] 2021-01-11 13:42
> Can you fix it or add pong method on websocket api ?

please read the [doc](https://www.boost.org/doc/libs/1_75_0/libs/beast/doc/html/beast/using_websocket/control_frames.html):
```
During read operations, Beast automatically reads and processes control frames. If a control callback is registered, the callback is notified of the incoming control frame. The implementation will respond to pings automatically. The receipt of a close frame initiates the WebSocket close procedure, eventually resulting in the error code error::closed being delivered to the caller in a subsequent read operation, assuming no other error takes place. 
```

**Comment by kyo06** [comment] 2021-01-16 08:37
OK thank you but I have still issues like
error on received markets fl=/mnt/c/Users/Sultan/Work/binapi/src/websocket.cpp(146), ec=2, errmsg: End of file
when I would like monitor all tickers
is it a problem with pong callback ?

**Comment by niXman** [comment] 2021-01-16 08:47
hi,

please provide me a complete example and describe how can I reproduce this.

**Comment by niXman** [comment] 2021-01-16 09:22
because [this](https://github.com/niXman/binapi/tree/master/examples/websockets) example runs without any problems for 30 minutes...
or use wireshark to analyze.

**Comment by kyo06** [comment] 2021-01-16 09:47
Here the code :

```
#include <binapi/api.hpp>
#include <binapi/websocket.hpp>

#include <boost/asio/io_context.hpp>

#include <iostream>

int main(int argc, char **argv) {

        boost::asio::io_context ioctx;
        binapi::ws::websockets_pool wsp(ioctx, "stream.binance.com", "9443");

        binapi::ws::websockets_pool::on_markets_received_cd callback_all_markets = [](const char *fl, int ec, std::string errmsg, binapi::ws::markets_tickers_t msg) -> bool {
            
            if ( ec ) {
                std::cerr << "error on received markets fl=" << fl << ", ec=" << ec << ", errmsg: " << errmsg << std::endl;
                return false;
            }
            return true;
        };
        
        wsp.subscribe_markets(callback_all_markets);

        std::cerr << "Connected..." << std::endl;
        ioctx.run();
        return 0;
}
```

**Comment by niXman** [comment] 2021-01-16 10:00
I think you are running into the message count limit...

ps
my test has been running successfully for an hour now.

**Comment by kyo06** [comment] 2021-01-16 11:28
Maybe the issue comes from the message count limit ... (I will investigate that) 
However there is no implementation for
- https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#individual-symbol-book-ticker-streams

- https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#all-book-tickers-stream

- https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#diff-depth-stream

Is it in your roadmap ?

**Comment by niXman** [comment] 2021-01-16 11:34
> Is it in your roadmap ?

no, I will look at this now...

but for the `diff-depth-stream`: https://github.com/niXman/binapi/blob/master/include/binapi/websocket.hpp#L77

**Comment by niXman** [comment] 2021-01-16 13:34
in master: https://github.com/niXman/binapi/commit/d4bac3c41856505facbef4677aeb86876a4ca6f7
test it please.

**Comment by kyo06** [comment] 2021-01-16 13:45
OK i will test it 👍

**Comment by niXman** [comment] 2021-01-18 14:00
hi,

any result? can I close this issue?

**Closed** 2021-01-19 07:10 UTC
